spring.application.name=franchise-hub

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/franchise_hub}
spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.webflux.problemdetails.enabled=true

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.issuer=${JWT_ISSUER:franchise-hub}
app.security.jwt.audience=${JWT_AUDIENCE:franchise-hub-api}
app.security.jwt.expiration=${JWT_EXPIRATION:PT30M}

app.security.demo-user.username=${FRANCHISE_APP_USERNAME}
app.security.demo-user.password=${FRANCHISE_APP_PASSWORD}

server.error.include-message=never
server.error.include-stacktrace=never
